/**
 * Seeds one demo user with a handful of orders covering every status
 * (pending, partially_paid, paid, overdue) plus a refund, so the app is
 * immediately explorable without manually creating data first.
 *
 * Run with: npm run seed
 * (loads .env.local via Node's --env-file flag, see package.json)
 */
import mongoose from "mongoose";
import bcrypt from "bcryptjs";
import { User } from "../src/lib/models/User";
import { Order } from "../src/lib/models/Order";
import { computeOrderTotals } from "../src/lib/logic/orderTotals";
import { computeStatus } from "../src/lib/logic/orderStatus";
import {
  computeNextStatusHistory,
  type StatusHistoryEntry,
} from "../src/lib/logic/statusHistory";

const DEMO_EMAIL = "demo@example.com";
const DEMO_PASSWORD = "password123";

const DAY_MS = 24 * 60 * 60 * 1000;

function daysFromNow(days: number): Date {
  return new Date(Date.now() + days * DAY_MS);
}

interface LifecycleStep {
  totalCents: number;
  amountPaidCents: number;
  dueDate: Date;
  at: Date;
}

/**
 * Builds an order's statusHistory the same way the live app does: replay
 * each lifecycle step (creation, payments, refunds, and — for the overdue
 * order — a later "read") through the exact same pure functions the API
 * routes use (computeStatus + computeNextStatusHistory). This makes the
 * seeded history indistinguishable from history a real user would have
 * generated by using the app, instead of a hand-typed approximation.
 */
function buildHistory(steps: LifecycleStep[]): StatusHistoryEntry[] {
  let history: StatusHistoryEntry[] = [];
  for (const step of steps) {
    const status = computeStatus(step, step.at);
    history = computeNextStatusHistory(history, status, step.at);
  }
  return history;
}

interface SeedLineItem {
  description: string;
  quantity: number;
  unitPriceCents: number;
}

interface SeedOrderInput {
  customer: string;
  dueDate: Date;
  lineItems: SeedLineItem[];
  payments: { type: "payment" | "refund"; amountCents: number; date: Date; note?: string }[];
  history: StatusHistoryEntry[];
}

async function seedOrder(userId: mongoose.Types.ObjectId, input: SeedOrderInput) {
  const { subtotalCents, totalCents } = computeOrderTotals(input.lineItems);
  const amountPaidCents = input.payments.reduce(
    (sum, payment) => sum + (payment.type === "refund" ? -payment.amountCents : payment.amountCents),
    0,
  );

  await Order.create({
    userId,
    customer: input.customer,
    dueDate: input.dueDate,
    lineItems: input.lineItems,
    payments: input.payments.map((payment) => ({ ...payment, createdAt: payment.date })),
    subtotalCents,
    totalCents,
    amountPaidCents,
    statusHistory: input.history,
  });
  console.log(`  - ${input.customer} (${computeStatus({ totalCents, amountPaidCents, dueDate: input.dueDate })})`);
}

async function main() {
  const uri = process.env.MONGODB_URI;
  if (!uri) {
    throw new Error("MONGODB_URI is not set. Make sure .env.local has it and run via `npm run seed`.");
  }

  await mongoose.connect(uri);
  console.log("Connected to MongoDB.");

  // Idempotent: wipe any previous run's demo data first so this can be
  // re-run freely without accumulating duplicate orders.
  const existingUser = await User.findOne({ email: DEMO_EMAIL });
  if (existingUser) {
    await Order.deleteMany({ userId: existingUser._id });
    await existingUser.deleteOne();
    console.log("Cleared previous demo data.");
  }

  const passwordHash = await bcrypt.hash(DEMO_PASSWORD, 10);
  const user = await User.create({ email: DEMO_EMAIL, passwordHash });

  const dueIn7Days = daysFromNow(7);
  const dueIn14Days = daysFromNow(14);
  const due10DaysAgo = daysFromNow(-10);

  console.log("Creating orders:");

  // 1. The assignment's exact sample scenario: a $1000 order, paid via a
  // $400 payment then a $600 payment -> fully paid.
  {
    const lineItems: SeedLineItem[] = [
      { description: "Widgets", quantity: 2, unitPriceCents: 50000 },
    ];
    const created = daysFromNow(-5);
    const firstPayment = daysFromNow(-3);
    const secondPayment = daysFromNow(-1);
    const { totalCents } = computeOrderTotals(lineItems);

    await seedOrder(user._id, {
      customer: "Acme Corp",
      dueDate: dueIn7Days,
      lineItems,
      payments: [
        { type: "payment", amountCents: 40000, date: firstPayment, note: "Initial deposit" },
        { type: "payment", amountCents: 60000, date: secondPayment, note: "Final payment" },
      ],
      history: buildHistory([
        { totalCents, amountPaidCents: 0, dueDate: dueIn7Days, at: created },
        { totalCents, amountPaidCents: 40000, dueDate: dueIn7Days, at: firstPayment },
        { totalCents, amountPaidCents: 100000, dueDate: dueIn7Days, at: secondPayment },
      ]),
    });
  }

  // 2. Pending: due in the future, no payments yet.
  {
    const lineItems: SeedLineItem[] = [
      { description: "Consulting hours", quantity: 10, unitPriceCents: 15000 },
    ];
    const created = daysFromNow(-1);
    const { totalCents } = computeOrderTotals(lineItems);

    await seedOrder(user._id, {
      customer: "Globex Inc",
      dueDate: dueIn14Days,
      lineItems,
      payments: [],
      history: buildHistory([
        { totalCents, amountPaidCents: 0, dueDate: dueIn14Days, at: created },
      ]),
    });
  }

  // 3. Overdue: due date already passed, still unpaid. The second history
  // step represents the lazy "noticed on a read" detection the real app
  // does for this exact transition.
  {
    const lineItems: SeedLineItem[] = [
      { description: "Equipment rental", quantity: 1, unitPriceCents: 75000 },
    ];
    const created = daysFromNow(-20);
    const { totalCents } = computeOrderTotals(lineItems);

    await seedOrder(user._id, {
      customer: "Initech",
      dueDate: due10DaysAgo,
      lineItems,
      payments: [],
      history: buildHistory([
        { totalCents, amountPaidCents: 0, dueDate: due10DaysAgo, at: created },
        { totalCents, amountPaidCents: 0, dueDate: due10DaysAgo, at: new Date() },
      ]),
    });
  }

  // 4. Paid in full, then partially refunded -> back to partially_paid.
  // Showcases the refund stretch goal and a non-monotonic status history.
  {
    const lineItems: SeedLineItem[] = [
      { description: "Design services", quantity: 1, unitPriceCents: 50000 },
    ];
    const created = daysFromNow(-6);
    const paymentAt = daysFromNow(-4);
    const refundAt = daysFromNow(-2);
    const { totalCents } = computeOrderTotals(lineItems);

    await seedOrder(user._id, {
      customer: "Umbrella Corp",
      dueDate: dueIn14Days,
      lineItems,
      payments: [
        { type: "payment", amountCents: 50000, date: paymentAt, note: "Paid in full" },
        { type: "refund", amountCents: 30000, date: refundAt, note: "Partial refund — scope reduced" },
      ],
      history: buildHistory([
        { totalCents, amountPaidCents: 0, dueDate: dueIn14Days, at: created },
        { totalCents, amountPaidCents: 50000, dueDate: dueIn14Days, at: paymentAt },
        { totalCents, amountPaidCents: 20000, dueDate: dueIn14Days, at: refundAt },
      ]),
    });
  }

  console.log("\nSeed complete. Log in with:");
  console.log(`  email:    ${DEMO_EMAIL}`);
  console.log(`  password: ${DEMO_PASSWORD}`);

  await mongoose.disconnect();
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
